In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# Autograd

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.3707, -0.0525,  0.5541], requires_grad=True)


In [ ]:
y = x + 2
print(y)

tensor([0.6293, 1.9475, 2.5541], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * 2
# z = z.mean()
print(z)

tensor([ 0.7921,  7.5855, 13.0468], grad_fn=<MulBackward0>)


In [ ]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([0.2517, 7.7900, 0.0102])


# Backpropagation

In [ ]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

In [ ]:
# Forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y) ** 2

print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [ ]:
# Backward pass
loss.backward()
print(w.grad)

tensor(-2.)


# Gradient Descent Numpy

In [ ]:
# f = w * x
# f = 2 * w

X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

In [ ]:
# model prediction
def forward(x):
  return w * x

In [ ]:
# loss = MSE
def loss(y, y_predicted):
  return ((y_predicted - y) ** 2).mean()

In [ ]:
# gradient
# MSE = 1/N * (w * x -y) ** 2
# dJ/dw = 1/N 2x (w * x - y)

def gradient(x, y, y_predicted):
  return np.dot(2*x, y_predicted-y).mean()

In [ ]:
print(f'Prediction before training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000


In [ ]:
# training
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
  # prediction = forward pass
  y_pred = forward(X)

  # loss
  l = loss(Y, y_pred)

  # gradients = backward pass
  dw = gradient(X, Y, y_pred)

  # update weights
  w -= learning_rate * dw

  if epoch % 2 == 0:
    print(f'epoch: {epoch+1}: w={w:.3f}, loss={l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

epoch: 1: w=1.200, loss=30.00000000
epoch: 3: w=1.872, loss=0.76800019
epoch: 5: w=1.980, loss=0.01966083
epoch: 7: w=1.997, loss=0.00050331
epoch: 9: w=1.999, loss=0.00001288
epoch: 11: w=2.000, loss=0.00000033
epoch: 13: w=2.000, loss=0.00000001
epoch: 15: w=2.000, loss=0.00000000
epoch: 17: w=2.000, loss=0.00000000
epoch: 19: w=2.000, loss=0.00000000
Prediction after training: f(5) = 10.000


# Gradient Descent Torch

In [ ]:
# f = w * x
# f = 2 * w

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [ ]:
# model prediction
def forward(x):
  return w * x

In [ ]:
# loss = MSE
def loss(y, y_predicted):
  return ((y_predicted - y) ** 2).mean()

In [ ]:
# training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  # prediction = forward pass
  y_pred = forward(X)

  # loss
  l = loss(Y, y_pred)

  # gradients = backward pass
  l.backward() # dl/dw

  # update weights
  with torch.no_grad():
    w -= learning_rate * w.grad

  # zero gradients
  w.grad.zero_()

  if epoch % 2 == 0:
    print(f'epoch: {epoch+1}: w={w:.3f}, loss={l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

epoch: 1: w=1.934, loss=0.04506890
epoch: 3: w=1.952, loss=0.02352631
epoch: 5: w=1.966, loss=0.01228084
epoch: 7: w=1.975, loss=0.00641066
epoch: 9: w=1.982, loss=0.00334642
epoch: 11: w=1.987, loss=0.00174685
epoch: 13: w=1.991, loss=0.00091188
epoch: 15: w=1.993, loss=0.00047601
epoch: 17: w=1.995, loss=0.00024848
epoch: 19: w=1.996, loss=0.00012971
epoch: 21: w=1.997, loss=0.00006770
epoch: 23: w=1.998, loss=0.00003534
epoch: 25: w=1.999, loss=0.00001845
epoch: 27: w=1.999, loss=0.00000963
epoch: 29: w=1.999, loss=0.00000503
epoch: 31: w=1.999, loss=0.00000262
epoch: 33: w=2.000, loss=0.00000137
epoch: 35: w=2.000, loss=0.00000071
epoch: 37: w=2.000, loss=0.00000037
epoch: 39: w=2.000, loss=0.00000019
epoch: 41: w=2.000, loss=0.00000010
epoch: 43: w=2.000, loss=0.00000005
epoch: 45: w=2.000, loss=0.00000003
epoch: 47: w=2.000, loss=0.00000001
epoch: 49: w=2.000, loss=0.00000001
epoch: 51: w=2.000, loss=0.00000000
epoch: 53: w=2.000, loss=0.00000000
epoch: 55: w=2.000, loss=0.000000

# Training Pipeline

In [ ]:
# 1) Design model (input, output size, forward pass)
# 2) Construct loss and optimizer
# 3) Training loop
# - forward pass: compute prediction
# - backward pass: gradients
# - update weights

In [ ]:
import torch.nn as nn

In [ ]:
# f = w * x
# f = 2 * w

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

X_test = torch.tensor([5], dtype=torch.float32)

n_samples, n_features = X.shape
print(n_samples, n_features)

4 1


In [ ]:
input_size = n_features
output_size = n_features

model = nn.Linear(input_size, output_size)

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

Prediction before training: f(5) = 4.503


In [ ]:
# training
learning_rate = 0.01
n_iters = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(n_iters):
  # prediction = forward pass
  y_pred = model(X)

  # loss
  l = loss(Y, y_pred)

  # gradients = backward pass
  l.backward() # dl/dw

  # update weights
  optimizer.step()

  # zero gradients
  optimizer.zero_grad()

  if epoch % 10 == 0:
    [w, b] = model.parameters()
    print(f'epoch: {epoch+1}: w={w[0][0].item():.3f}, loss={l:.8f}')

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

epoch: 1: w=1.790, loss=0.06386760
epoch: 11: w=1.796, loss=0.06015017
epoch: 21: w=1.803, loss=0.05664911
epoch: 31: w=1.808, loss=0.05335178
epoch: 41: w=1.814, loss=0.05024648
epoch: 51: w=1.819, loss=0.04732185
epoch: 61: w=1.825, loss=0.04456754
epoch: 71: w=1.830, loss=0.04197349
epoch: 81: w=1.835, loss=0.03953036
epoch: 91: w=1.840, loss=0.03722950
Prediction after training: f(5) = 9.679
