In [9]:
import torch
import torch.nn as nn

In [10]:
class Model(nn.Module):
  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.linear(x))
    return y_pred

In [17]:
model = Model(n_input_features=6)

In [18]:
FILE = 'model.pth'
# torch.save(model, FILE)

In [19]:
# model = torch.load(FILE)
# model.eval()

In [20]:
torch.save(model.state_dict(), FILE)

In [23]:
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [25]:
print('Parameters of normal model:')
for param in model.parameters():
  print(param)

print('\nParameters of loaded model:')
for param in loaded_model.parameters():
  print(param)

Parameters of normal model:
Parameter containing:
tensor([[-0.3911,  0.1635,  0.3484, -0.3115,  0.0433, -0.2030]],
       requires_grad=True)
Parameter containing:
tensor([-0.2587], requires_grad=True)

Parameters of loaded model:
Parameter containing:
tensor([[-0.3911,  0.1635,  0.3484, -0.3115,  0.0433, -0.2030]],
       requires_grad=True)
Parameter containing:
tensor([-0.2587], requires_grad=True)
